/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppApiKeysRouteImport } from './routes/app/api-keys'
import { Route as AppMembersRouteImport } from './routes/app/members'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppUsageRouteImport } from './routes/app/usage'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1KnowledgeBasesRouteImport } from './routes/api/v1/knowledge-bases'
import { Route as AppAssistantIndexRouteImport } from './routes/app/assistant/index'
import { Route as AppKnowledgeIndexRouteImport } from './routes/app/knowledge/index'
import { Route as AppKnowledgeKbIdRouteImport } from './routes/app/knowledge/$kbId'
import { Route as ApiV1AssistantQueryRouteImport } from './routes/api/v1/assistant/query'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1KnowledgeBasesRoute = ApiV1KnowledgeBasesRouteImport.update({
  id: '/api/v1/knowledge-bases',
  path: '/api/v1/knowledge-bases',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAssistantIndexRoute = AppAssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKnowledgeIndexRoute = AppKnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKnowledgeKbIdRoute = AppKnowledgeKbIdRouteImport.update({
  id: '/knowledge/$kbId',
  path: '/knowledge/$kbId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiV1AssistantQueryRoute = ApiV1AssistantQueryRouteImport.update({
  id: '/api/v1/assistant/query',
  path: '/api/v1/assistant/query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/members': typeof AppMembersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/docs/api': typeof DocsApiRoute
  '/join/$token': typeof JoinTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/knowledge-bases': typeof ApiV1KnowledgeBasesRoute
  '/app/knowledge/$kbId': typeof AppKnowledgeKbIdRoute
  '/app/assistant/': typeof AppAssistantIndexRoute
  '/app/knowledge/': typeof AppKnowledgeIndexRoute
  '/api/v1/assistant/query': typeof ApiV1AssistantQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/members': typeof AppMembersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/docs/api': typeof DocsApiRoute
  '/join/$token': typeof JoinTokenRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/knowledge-bases': typeof ApiV1KnowledgeBasesRoute
  '/app/knowledge/$kbId': typeof AppKnowledgeKbIdRoute
  '/app/assistant': typeof AppAssistantIndexRoute
  '/app/knowledge': typeof AppKnowledgeIndexRoute
  '/api/v1/assistant/query': typeof ApiV1AssistantQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/members': typeof AppMembersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/docs/api': typeof DocsApiRoute
  '/join/$token': typeof JoinTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/knowledge-bases': typeof ApiV1KnowledgeBasesRoute
  '/app/knowledge/$kbId': typeof AppKnowledgeKbIdRoute
  '/app/assistant/': typeof AppAssistantIndexRoute
  '/app/knowledge/': typeof AppKnowledgeIndexRoute
  '/api/v1/assistant/query': typeof ApiV1AssistantQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/app/api-keys'
    | '/app/members'
    | '/app/settings'
    | '/app/usage'
    | '/docs/api'
    | '/join/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/v1/knowledge-bases'
    | '/app/knowledge/$kbId'
    | '/app/assistant/'
    | '/app/knowledge/'
    | '/api/v1/assistant/query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/app/api-keys'
    | '/app/members'
    | '/app/settings'
    | '/app/usage'
    | '/docs/api'
    | '/join/$token'
    | '/app'
    | '/api/auth/$'
    | '/api/v1/knowledge-bases'
    | '/app/knowledge/$kbId'
    | '/app/assistant'
    | '/app/knowledge'
    | '/api/v1/assistant/query'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/app/api-keys'
    | '/app/members'
    | '/app/settings'
    | '/app/usage'
    | '/docs/api'
    | '/join/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/v1/knowledge-bases'
    | '/app/knowledge/$kbId'
    | '/app/assistant/'
    | '/app/knowledge/'
    | '/api/v1/assistant/query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  DocsApiRoute: typeof DocsApiRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1KnowledgeBasesRoute: typeof ApiV1KnowledgeBasesRoute
  ApiV1AssistantQueryRoute: typeof ApiV1AssistantQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/knowledge-bases': {
      id: '/api/v1/knowledge-bases'
      path: '/api/v1/knowledge-bases'
      fullPath: '/api/v1/knowledge-bases'
      preLoaderRoute: typeof ApiV1KnowledgeBasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/assistant/': {
      id: '/app/assistant/'
      path: '/assistant'
      fullPath: '/app/assistant/'
      preLoaderRoute: typeof AppAssistantIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/knowledge/': {
      id: '/app/knowledge/'
      path: '/knowledge'
      fullPath: '/app/knowledge/'
      preLoaderRoute: typeof AppKnowledgeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/knowledge/$kbId': {
      id: '/app/knowledge/$kbId'
      path: '/knowledge/$kbId'
      fullPath: '/app/knowledge/$kbId'
      preLoaderRoute: typeof AppKnowledgeKbIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/assistant/query': {
      id: '/api/v1/assistant/query'
      path: '/api/v1/assistant/query'
      fullPath: '/api/v1/assistant/query'
      preLoaderRoute: typeof ApiV1AssistantQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppMembersRoute: typeof AppMembersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppKnowledgeKbIdRoute: typeof AppKnowledgeKbIdRoute
  AppAssistantIndexRoute: typeof AppAssistantIndexRoute
  AppKnowledgeIndexRoute: typeof AppKnowledgeIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppMembersRoute: AppMembersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
  AppKnowledgeKbIdRoute: AppKnowledgeKbIdRoute,
  AppAssistantIndexRoute: AppAssistantIndexRoute,
  AppKnowledgeIndexRoute: AppKnowledgeIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  DocsApiRoute: DocsApiRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1KnowledgeBasesRoute: ApiV1KnowledgeBasesRoute,
  ApiV1AssistantQueryRoute: ApiV1AssistantQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
